import type { Metadata } from "next";
import "./globals.css";
import ApolloWrapper from "./providers/ApolloWrapper";
import Navbar from "./components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background text-gray-900">
        <ApolloWrapper>
          <Navbar />
          <main className="container mx-auto px-4 py-6">
            {children}
          </main>
        </ApolloWrapper>
      </body>
    </html>
  );
}
